import logo from "./logo.svg";
import "./App.css";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>This React Project was generated by Open-Set-Go, Open-Source Project starter</p>
        <a className="App-link" href="https://open-set-go.com" target="_blank" rel="noopener noreferrer">
          Learn Open-Set-Go
        </a>
      </header>
    </div>
  );
}

export default App;
